//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaBobsPizza.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaOrder
    {
        public System.Guid OrderId { get; set; }
        public MegaBobsPizza.DTO.Enums.PizzaSize Size { get; set; }
        public MegaBobsPizza.DTO.Enums.PizzaCrust Crust { get; set; }
        public bool Sausage { get; set; }
        public bool Pepperoni { get; set; }
        public bool Onions { get; set; }
        public bool GreenPeppers { get; set; }
        public decimal TotalCost { get; set; }
        public string Name { get; set; }
        public bool Completed { get; set; }
    }
}
